### ISSUE TITLE
Error on demo unpaired_ct_lung

### ISSUE THREAD

**Issue by QianyeYang** [DeepRegNet/DeepReg#350]
# Issue description
Cannot train the demo using `python3 demos/unpaired_ct_lung/demo_train.py`

## Type of Issue
- [x] Bug report

1. OS: Ubuntu 18.04
2. Environment to reproduce: DeepReg v0.1.6

Debug info:
```
2020-08-27 10:18:51.383868: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-27 10:18:51.386917: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-08-27 10:18:51.386945: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: yipeng-Precision-Tower-5810
2020-08-27 10:18:51.386950: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: yipeng-Precision-Tower-5810
2020-08-27 10:18:51.386996: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 430.50.0
2020-08-27 10:18:51.387020: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 430.50.0
2020-08-27 10:18:51.387027: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 430.50.0
2020-08-27 10:18:51.387222: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-08-27 10:18:51.409746: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3591920000 Hz
2020-08-27 10:18:51.410483: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b249022fe0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-27 10:18:51.410524: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-27 10:18:53.548395: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... 
Epoch 1/1500
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

**Comment by s-sd** [comment]
@QianyeYang, this error usually means that the available memory was not enough. Could you try running this on a GPU on one of the weiss machines. You will just need to change the gpu option in the train script to `gpu = "0, 1"`. Also if you are using a GPU, could you please make sure that it does not have other processes running on it which might be taking up memory. Let me know if you get the error when running on the GPU.

**Comment by QianyeYang** [comment]
Thanks @s-sd ! I found the reasons are not all related to the memory issue. The `gpu` parameter was not set in the train script, will it be better if we put a default value there? After setting `gpu="0"`, I can train the demo with a smaller batch size (=2) on a 24GB GPU. Therefore I suggest clarifying this memory issue in the readme.

**Comment by s-sd** [comment]
Great, thanks @QianyeYang! I will update it to use one or two GPUs by default and I'll write a note in the readme

**Comment by QianyeYang** [comment]
Thanks, @s-sd. Just in case, could you approve the PR(https://github.com/DeepRegNet/DeepReg/pull/351) for this demo before you make a further modification? Just fixed a bad link and adjust the structure of the readme.
